/* 
 * File:   assemblyLANG.h
 * Author: hq4ever
 *
 * Created on March 12, 2010, 10:53 PM
 */

#ifndef _ASSEMBLYLANG_H
#define	_ASSEMBLYLANG_H

#define ASM_LANG_CMD_MOV_CODE 000
#define ASM_LANG_CMD_CMP_CODE 001
#define ASM_LANG_CMD_ADD_CODE 002
#define ASM_LANG_CMD_SUB_CODE 003
#define ASM_LANG_CMD_MUL_CODE 004
#define ASM_LANG_CMD_DIV_CODE 005
#define ASM_LANG_CMD_LEA_CODE 006
#define ASM_LANG_CMD_INC_CODE 007
#define ASM_LANG_CMD_DEC_CODE 010
#define ASM_LANG_CMD_JMP_CODE 011
#define ASM_LANG_CMD_BNE_CODE 012
#define ASM_LANG_CMD_RED_CODE 013
#define ASM_LANG_CMD_PRN_CODE 014
#define ASM_LANG_CMD_JSR_CODE 015
#define ASM_LANG_CMD_RTS_CODE 016
#define ASM_LANG_CMD_HLT_CODE 017

#define ASM_LANG_ADDR_NO_OP     0
#define ASM_LANG_ADDR_IMMIDIATE 0
#define ASM_LANG_ADDR_DIRECT    1
#define ASM_LANG_ADDR_INDIRECT  3
#define ASM_LANG_ADDR_REGISTER  4

#endif	/* _ASSEMBLYLANG_H */

